import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.TestInstance
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.Arguments
import org.junit.jupiter.params.provider.MethodSource
import org.junit.jupiter.params.provider.ValueSource
import shared.Input
import kotlin.test.Test

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class Day11KtTest {
    private val input = Input("""
        ...#......
        .......#..
        #.........
        ..........
        ......#...
        .#........
        .........#
        ..........
        .......#..
        #...#.....
    """.trimIndent())

    @Test
    fun expandUniverse() {
        val result = expandUniverse(input)
        val expected = """
            ....#........
            .........#...
            #............
            .............
            .............
            ........#....
            .#...........
            ............#
            .............
            .............
            .........#...
            #....#.......
        """.trimIndent()
        assertEquals(expected, result)
    }

    @Test
    fun day11A() {
        val result = day11A(input)
        assertEquals(374, result)
    }

    @Test
    fun day11B() {
        val result = day11B(input, 10)
        assertEquals(1030, result)
    }
}